name       : gbenchmark
version    : 1.5.5
release    : 1
source     :
    - https://github.com/google/benchmark/archive/v1.5.5/benchmark-v1.5.5.tar.gz : 3bff5f237c317ddfd8d5a9b96b3eede7c0802e799db520d38ce756a2a46a18a0
homepage   : https://github.com/google/benchmark
license    : Apache-2.0
component  : programming.library
summary    : A microbenchmark support library
description: |
    A library that benchmarks code snippets, similar to unit tests.
setup      : |
    sed "s|@VERSION@|%version%|g" $pkgfiles/cmake-project-version.patch > cmake-project-version.patch
    %patch -p1 < cmake-project-version.patch
    %cmake_ninja -DBUILD_SHARED_LIBS=ON -DBENCHMARK_ENABLE_LTO=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
