name       : gbenchmark
version    : 1.6.1
release    : 3
source     :
    - https://github.com/google/benchmark/archive/v1.6.1/benchmark-v1.6.1.tar.gz : 6132883bc8c9b0df5375b16ab520fac1a85dc9e4cf5be59480448ece74b278d4
homepage   : https://github.com/google/benchmark
license    : Apache-2.0
component  : programming.library
summary    : A microbenchmark support library
description: |
    A library that benchmarks code snippets, similar to unit tests.
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON \
                 -DBENCHMARK_ENABLE_LTO=ON \
                 -DBENCHMARK_ENABLE_GTEST_TESTS=OFF \
                 -DBENCHMARK_INSTALL_DOCS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
